fix: Print error from token exchange endpoint.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -72,8 +72,11 @@ runs:
             -H "x-actions-token: $ACTIONS_TOKEN" \
             -H "x-installation-id: $PLATFORM_INSTALLATION_ID" \
             $PLATFORM_TOKEN_EXCHANGE_URL)
-        echo 'Resopnse:'
-        echo "$RESPONSE"
+        ERROR=$(echo "$RESPONSE" | jq -er '.error')
+        if [ -z $ERROR ]; then
+          echo "Error: $ERROR"
+          exit 1
+        fi
         echo token=$(echo "$RESPONSE" | jq -er '.token') >> $GITHUB_OUTPUT
         echo status=$(echo "$RESPONSE" | jq -er '.status') >> $GITHUB_OUTPUT
         # TODO: Fail step/action on bad status.
